name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    # Auto-detect and install dependencies
    - name: Setup Python (if requirements.txt exists)
      if: contains(github.event.repository.contents, 'requirements.txt')
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Python dependencies
      if: contains(github.event.repository.contents, 'requirements.txt')
      run: |
        pip install -r requirements.txt

    - name: Setup Node.js (if package.json exists)
      if: contains(github.event.repository.contents, 'package.json')
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install Node.js dependencies
      if: contains(github.event.repository.contents, 'package.json')
      run: |
        npm install
        npm run build --if-present

    # Run your app (modify this per your startup command)
    - name: Start application
      run: |
        if [ -f "app.py" ]; then
          nohup python app.py > server.log 2>&1 &
        elif [ -f "index.js" ]; then
          nohup node index.js > server.log 2>&1 &
        fi
        sleep 5
        cat server.log

    # Simple test - verify the app starts (customize this)
    - name: Smoke test
      run: |
        curl -s http://localhost:5000 || curl -s http://localhost:3000

    # Optional: Deploy to Vercel/Render (uncomment and add secrets)
    # - name: Deploy to Vercel
    #   uses: amondnet/vercel-action@v25
    #   with:
    #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
    #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
