name: Build Android APK  # 👈 Line 1 (must start with 'name')

on: [push]  # 👈 Line 3 (simplified trigger syntax)

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build APK
      run: ./gradlew assembleDebug
